### ISSUE TITLE
tensorRT version mismatch

### ISSUE THREAD

**Issue by julinfn** [mingj2021/segment-anything-tensorrt#2]
hello，what's the verion of tensorRT used to generate .engine file? i test the provided .engine file on my computer, it seems there is a version problem. tensorRT on my computer is 8.4.1.5 . thks.
```
all characters read successfully.
1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::StdArchiveReader::40] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 213, Serialized Engine Version: 232)
4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
```

**Comment by mingj2021** [comment]
.engine file unlike onnx which generate once,running everywhere, the .engine model In close contact with the graphics card，so you get a error,i think . you can generate .engine file by yourself, quant-onnx format model  can not transform into .engine file,  try again , all my provided scripts and *.cpp files tested successfully on docker virtual env.

**Comment by mingj2021** [comment]
export_embedding_model()
export_sam_model()
onnx_model_example()
export_engine_image_encoder()
export_engine_prompt_encoder_and_mask_decoder()
the quant-onnx model can not transform into .engine file, step by step ,you can get .engine model,

**Comment by julinfn** [comment]
> export_embedding_model() export_sam_model() onnx_model_example() export_engine_image_encoder() export_engine_prompt_encoder_and_mask_decoder() the quant-onnx model can not transform into .engine file, step by step ,you can get .engine model,

thks.
