### ISSUE TITLE
Why not add orig_im_size

### ISSUE THREAD

**Issue by BooHwang** [mingj2021/segment-anything-tensorrt#4]
Hi, I notice you have delete params "orig_img_size" while convert pth weights to onnx, why not add this params?

**Comment by mingj2021** [comment]
tensorrt surport "dynamic shape",but you add the params "orig_img_size", tensorrt framework can not dynamic infer the output shape,so, you can not allocate memory for output variable. when export model using in other Deep learning framework ,we should delete "post process partly code". the params "orig_img_size" using in post-process.

**Comment by YzbDoMore** [comment]
> tensorrt surport "dynamic shape",but you add the params "orig_img_size", tensorrt framework can not dynamic infer the output shape,so, you can not allocate memory for output variable. when export model using in other Deep learning framework ,we should delete "post process partly code". the params "orig_img_size" using in post-process.

Can you provide the code of this part
